version: '2'

services:
  web:
    volumes:
    - ./db.sqlite3:/app/db.sqlite3
    - ./configFile/nginx.conf:/etc/nginx/nginx.conf
    - ./configFile/autocrawl-nginx.conf:/etc/nginx/conf.d/autocrawl-nginx.conf
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./chromedriver:/app/chromedriver
    - ./geckodriver:/app/geckodriver
    - ./cert/user_certificate.crt:/app/cert/user_certificate.crt
    - ./cert/user_private.key:/app/cert/user_private.key
    build: .
    image: autocrawl_web:v1.0
    dns:
        - 8.8.8.8
    ports:
      - "80:80"
      - "443:443"